---
# This playbook initialize a Debian 11 installation and transforms it into a Proxmox VE server (version 7.4)
# Based on the official documentation at https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye

- name: Install Proxmox VE 7 on Debian 11
  hosts: target
  become: true
  tasks:
  - name: Upgrade dist
    apt:
      upgrade: dist

  - name: Overwrite the /etc/hosts config file
    template:
      src: hosts.j2
      dest: /etc/hosts

  - name: Add Proxmox VE repository
    lineinfile:
      path: /etc/apt/sources.list.d/pve-install-repo.list
      line: 'deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
      create: yes

  - name: Download Proxmox VE repository key
    get_url:
      url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
      dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg

  - name: Update repository and system
    apt:
      update_cache: yes
      upgrade: full

  - name: Install Proxmox VE kernel
    apt:
      name: pve-kernel-5.15
      state: present
    register: kernel_install

  - name: Reboot system
    reboot:
      connect_timeout: 60
    when: kernel_install.changed

  - name: Install Proxmox VE packages
    apt:
      name:
        - proxmox-ve
        - postfix
        - open-iscsi
      state: present
    register: proxmox_install_packages

  - name: Delete file with apt source reserved for paid subscription
    file:
      path: /etc/apt/sources.list.d/pve-enterprise.list
      state: absent

  - name: Remove Debian kernel & os-prober package
    apt:
      name:
        - linux-image-amd64
        - 'linux-image-5.10*'
        - os-prober
      state: absent

  - name: Update grub2 configuration
    command: update-grub

  - name: Delete pop-up message for paid subscription
    shell: sed -i.backup -z "s/res === null || res === undefined || \!res || res\n\t\t\t.data.status.toLowerCase() \!== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && systemctl restart pveproxy.service

  - name: Reboot system
    reboot:
      connect_timeout: 60
    when: proxmox_install_packages.changed

  - name: Overwrite the /etc/network/interfaces config file
    template:
      src: interfaces.j2
      dest: /etc/network/interfaces

  - name: Enable the Linux Bridge interfaces - vmbr0 for standard network and vmbr1 for NAT network
    shell: ifup vmbr0 && ifup vmbr1

  - name: Reboot system
    reboot:
      connect_timeout: 60
    when: proxmox_install_packages.changed

  - name: Done!
    debug:
      msg: "Proxmox VE installed successfully! You can now access the web interface at https://{{ ansible_default_ipv4.address }}:8006/"
