---
# This playbook initialize a Debian 11 installation and transforms it into a Proxmox VE server (version 7.4)
# Based on the official documentation at https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye

- name: Install Proxmox VE 7 on Debian 11
  become: yes
  hosts: baremetal
  roles:
    - proxmox-installer
